package gitops

import "fmt"

// BuildPRBody generates a markdown description for a deployment pull request.
// mode should be "github" (dry-run) or "aws" (real deployment).
func BuildPRBody(tfFile, branch, mode string) string {
	bt := "`"
	modeLine := "GitHub Actions (dry-run)"
	if mode == "aws" {
		modeLine = "AWS (real deployment)"
	}

	return fmt.Sprintf(
		"## InfraSage Generated Infrastructure\n\n"+
			"**File:** "+bt+"%s"+bt+"\n"+
			"**Branch:** "+bt+"%s"+bt+"\n"+
			"**Mode:** "+bt+"%s"+bt+"\n\n"+
			"### What this PR does\n"+
			"This Terraform file was generated by [InfraSage](https://github.com/Sahil0114/infrasage1)\n"+
			"from a natural language prompt and automatically scanned for security issues.\n\n"+
			"### Pre-merge checklist\n"+
			"- [ ] Review the generated Terraform HCL\n"+
			"- [ ] Check the security scan results (Checkov / tfsec / Terrascan)\n"+
			"- [ ] Verify the correct AWS region and account\n"+
			"- [ ] Confirm resource naming follows your conventions\n\n"+
			"### CI/CD\n"+
			"- Checkov, tfsec, and Terrascan will re-scan in CI\n"+
			"- Terraform plan will run and post output on this PR\n"+
			"- Merging will trigger "+bt+"terraform apply"+bt+" when AWS mode is enabled\n\n"+
			"---\n"+
			"*Generated by InfraSage CLI — AI-powered DevSecOps*",
		tfFile, branch, modeLine,
	)
}
