package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/Sahil0114/infrasage1/internal/gitops"
	"github.com/Sahil0114/infrasage1/internal/monitor"
	"github.com/Sahil0114/infrasage1/internal/scanner"
	"github.com/spf13/cobra"
)

var (
	deployBranch  string
	deployMessage string
	deployForce   bool
)

var deployCmd = &cobra.Command{
	Use:   "deploy <file>",
	Short: "Commit a Terraform file, push a branch, and open a GitHub pull request",
	Long: `deploy commits the given Terraform file to a new git branch, pushes it
to origin, and opens a pull request on GitHub.

Requirements:
  - GITHUB_TOKEN must be set in .env (needs 'repo' scope)
  - GITHUB_REPO must be set in .env (format: owner/repo-name)
  - The current directory must be inside a git repository
  - The file must already be generated (run 'infrasage ask' first)

Example:
  infrasage deploy infra.tf
  infrasage deploy ec2.tf --branch feat/add-ec2 --message "Add EC2 instance"`,
	Args: cobra.ExactArgs(1),
	RunE: runDeploy,
}

func init() {
	deployCmd.Flags().StringVar(
		&deployBranch, "branch", "",
		"Git branch name to create (default: infrasage/<basename-without-ext>-<timestamp>)",
	)
	deployCmd.Flags().StringVar(
		&deployMessage, "message", "",
		"Git commit message (default: derived from filename)",
	)
	deployCmd.Flags().BoolVar(
		&deployForce, "force", false,
		"Force-add file even if ignored by git",
	)
	rootCmd.AddCommand(deployCmd)
}

func runDeploy(cmd *cobra.Command, args []string) error {
	tfFile := args[0]

	// Verify the file exists before doing any git work.
	if _, err := os.Stat(tfFile); err != nil {
		return fmt.Errorf("deploy: file not found: %q\nFix: run 'infrasage ask \"...\"' first to generate the file.", tfFile)
	}

	// Derive branch name if not provided.
	if deployBranch == "" {
		base := filepath.Base(tfFile)
		noExt := base[:len(base)-len(filepath.Ext(base))]
		ts := time.Now().Format("20060102-150405")
		deployBranch = fmt.Sprintf("infrasage/%s-%s", noExt, ts)
	}

	// Derive commit message if not provided.
	if deployMessage == "" {
		deployMessage = fmt.Sprintf("chore(infrasage): add %s", filepath.Base(tfFile))
	}

	fmt.Printf("🚀 Deploying %s\n", tfFile)
	fmt.Printf("   Branch:  %s\n", deployBranch)
	fmt.Printf("   Message: %s\n\n", deployMessage)

	fmt.Println("🔍 Running pre-deploy security scan...")
	report, err := scanner.RunAll(tfFile)
	if err != nil {
		return fmt.Errorf("deploy: pre-deploy scan failed: %w\nFix: run 'infrasage stack up' to start scanner containers.", err)
	}
	report.Print()
	monitor.RecordScan(report)

	if report.HasCritical() {
		return fmt.Errorf("deploy: blocked due to CRITICAL findings\nFix: run 'infrasage fix %s' or remediate manually, then retry deploy.", tfFile)
	}

	// Step 1: commit and push.
	fmt.Println("📦 Committing and pushing branch...")
	if err := gitops.CommitAndPush(tfFile, deployBranch, deployMessage, deployForce); err != nil {
		return fmt.Errorf("deploy: git step failed: %w", err)
	}
	fmt.Printf("✅ Branch pushed: %s\n\n", deployBranch)

	// Step 2: open a pull request.
	fmt.Println("🔗 Opening GitHub pull request...")
	prTitle := fmt.Sprintf("[InfraSage] %s", deployMessage)
	prBody := buildPRBody(tfFile, deployBranch)

	prURL, err := gitops.CreatePR(deployBranch, prTitle, prBody)
	if err != nil {
		return fmt.Errorf("deploy: creating PR failed: %w", err)
	}

	fmt.Printf("✅ Pull request opened: %s\n", prURL)
	fmt.Printf("\nNext steps:\n")
	fmt.Printf("  1. Review the PR at the URL above\n")
	if os.Getenv("AWS_ACCESS_KEY_ID") != "" && os.Getenv("AWS_SECRET_ACCESS_KEY") != "" {
		fmt.Printf("  2. Merge to trigger the optional real-apply workflow\n")
		fmt.Printf("  3. Monitor drift with: infrasage drift\n")
	} else {
		fmt.Printf("  2. CI will run scanners and Terraform dry-run simulation (no AWS mode)\n")
		fmt.Printf("  3. Add AWS secrets later to enable real cloud apply/drift workflows\n")
	}

	return nil
}

// buildPRBody generates a markdown description for the pull request.
func buildPRBody(tfFile, branch string) string {
	bt := "`"
	return fmt.Sprintf(
		"## InfraSage Generated Infrastructure\n\n"+
			"**File:** "+bt+"%s"+bt+"\n"+
			"**Branch:** "+bt+"%s"+bt+"\n\n"+
			"### What this PR does\n"+
			"This Terraform file was generated by [InfraSage](https://github.com/Sahil0114/infrasage1)\n"+
			"from a natural language prompt and automatically scanned for security issues.\n\n"+
			"### Pre-merge checklist\n"+
			"- [ ] Review the generated Terraform HCL\n"+
			"- [ ] Check the security scan results (Checkov / tfsec / Terrascan)\n"+
			"- [ ] Verify the correct AWS region and account\n"+
			"- [ ] Confirm resource naming follows your conventions\n\n"+
			"### CI/CD\n"+
			"- Checkov, tfsec, and Terrascan will re-scan in CI\n"+
			"- Terraform dry-run simulation runs automatically (no AWS mode)\n"+
			"- Real cloud apply/drift can be enabled later by adding AWS secrets\n\n"+
			"---\n"+
			"*Generated by InfraSage CLI — AI-powered DevSecOps*",
		tfFile, branch,
	)
}
